### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by karahanyilmazer** [PlotJuggler/plotjuggler-lsl#2]
I am trying to install the plugin using an Ubuntu terminal on Windows. I could build PlotJuggler and it works without any problems. When I try to build the plotjuggler-lsl plugin, I get the following error:

_**CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PlotJuggler (missing: PlotJuggler_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPlotJuggler.cmake:56 (find_package_handle_standard_args)
  CMakeLists.txt:96 (find_package)_**_

I tried cloning the directory to different folders, including directly inside the PlotJuggler folder but to no avail. Could you please help me building the plugin?

**Comment by csavur** [comment]
@karahanyilmazer It has been some time, but I updated the CMakeFile  and Readme files so you should be able to compile on windows...
